version: '3.7'

services:
  nginx:
    container_name: nginx-em
    build:
      context: docker/nginx
    image: nginx
    volumes:
      - ./:/var/www
      - ./storage/app/public/:/var/www/public/storage/
    ports:
      - "8001:80"
    depends_on:
      - php-fpm
    networks:
      - internal

  php-fpm:
    container_name: php-fpm-em
    build:
      context: docker/php-fpm
    image: php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - internal

  db:
    container_name: pgsql-em  # mysql-em
    build: ./docker/pgsql     # mysql
    image: pgsql              # mysql
    ports:
      - "5434:5432"           # "3308:3306"
    volumes:
#      - ./docker/pgsql/init:/docker-entrypoint-initdb.d                                       # ./docker/mysql/init
      - ./backup/latest/em_pg-latest.sql.gz:/docker-entrypoint-initdb.d/em_pg-latest.sql.gz   # ./backup/latest/em_my-latest.sql.gz
      - ./docker/pgsql/pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE_PG}       # MYSQL_DB
      - POSTGRES_USER=${DB_USERNAME_PG}     # MYSQL_USER
      - POSTGRES_PASSWORD=${DB_PASSWORD_PG} # MYSQL_PASSWORD
    networks:
      - internal

  pgbackup:
    container_name: backup-em
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_DATABASE_PG}
      - POSTGRES_USER=${DB_USERNAME_PG}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PG}
      - POSTGRES_EXTRA_OPTS=-Z9
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=83
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
