version: '3.7'

services:
  db-em:
    container_name: pgsql
    build: ./docker/pgsql
    image: pgsql
    ports:
      - "5434:5432"
    volumes:
#      - ./docker/pgsql/init:/docker-entrypoint-initdb.d
      - ./backup/daily/em_pg-latest.sql.gz:/docker-entrypoint-initdb.d/em_pg-latest.sql.gz
      - ./docker/pgsql/pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE_PG}
      - POSTGRES_USER=${DB_USERNAME_PG}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PG}
    networks:
      - internal

  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
    image: php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db-em
    networks:
      - internal

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    image: nginx
    volumes:
      - ./:/var/www
      - ./storage/app/public/:/var/www/public/storage/
    ports:
      - "8001:80"
    depends_on:
      - php-fpm
    networks:
      - internal

  #db-em:
    #container_name: mysql
    #build: ./docker/mysql
    #image: mysql
    #ports:
      #- "3308:3306"
    #volumes:
      #- ./docker/mysql/init:/docker-entrypoint-initdb.d
      #- ./docker/mysql/mydata:/var/lib/mysql
    #environment:
      #- MYSQL_DB=${DB_DATABASE}
      #- MYSQL_USER=${DB_USERNAME}
      #- MYSQL_PASSWORD=${DB_PASSWORD}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
    #networks:
      #- internal

  pgbackup:
    container_name: backup-em
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db-em:db-em
    depends_on:
      - db-em
    environment:
      - POSTGRES_HOST=db-em
      - POSTGRES_DB=${DB_DATABASE_PG}
      - POSTGRES_USER=${DB_USERNAME_PG}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PG}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=83

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
